[theme]
base = "light"
primaryColor = "#1F5673"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#12263A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
maxUploadSize = 5
